name: CI with GitHub Actions using Ant and JUnit | © 2022 by phuocson

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check-out repository
        uses: actions/checkout@v4  # Sử dụng phiên bản mới nhất của actions/checkout

      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'temurin'

      - name: Build project with Ant
        run: ant -noinput -buildfile build.xml

      - name: Run JUnit Tests
        run: ant -noinput -buildfile build.xml test

      - name: Distribute jar-war file
        run: mkdir -p staging && cp dist/*.jar staging

      - name: Upload Artifact
        uses: actions/upload-artifact@v4  # Sử dụng phiên bản v4 của actions/upload-artifact
        with:
          name: 1.0-SNAPSHOT.jar
          path: staging
